CREATE TABLE EMPLOYEE_DETAILS (
EMPLOYEE_ID SERIAL UNIQUE,
FIRST_NAME VARCHAR(50), 
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(100), 
PHONE_NUMBER VARCHAR(15),
HIRE_DATE DATE,
SALARY DECIMAL(10,2),
DEPARTMENT_ID INT,
IS_ACTIVE BOOLEAN,
JOB_TITLE VARCHAR(100));

SELECT * FROM EMPLOYEE_DETAILS;

INSERT INTO EMPLOYEE_DETAILS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL,
PHONE_NUMBER, HIRE_DATE, SALARY, DEPARTMENT_ID, IS_ACTIVE, JOB_TITLE)
VALUES (1,'Abhay','Shahakar', 'abhay@example.com', 
9856742312, '2018-05-1', 30000, 2, 'Yes', 'Project Manager'),
(2,'Bhavana','Jaiswal', 'bhavana@example.com', 
9765124598, '01-04-2019', 40000, 1, 'Yes', 'Graphic Designer'),
(3,'Chetna','Raje', 'chetna@example.com', 
9656789812, '2020-03-1', 50000, 3, 'No', 'HR Manager'),
(4,'Dhani','Pawar', 'dhani@example.com', 
8798451236, '2021-02-1', 80000, 5, 'No', 'Business_Analyst'),
(5,'Elize','Shawn', 'elize@example.com', 
8897452564, '2022-01-1', 100000, 4, 'YES', 'Software Tester');

copy EMPLOYEE_DETAILS FROM 'D:\IMP\DA-13\DA-13\Employee_Details.csv'
delimiter ',' csv header;

update EMPLOYEE_DETAILS SET department_id = 0 WHERE IS_ACTIVE = 'false';

UPDATE EMPLOYEE_DETAILS SET salary = salary * 1.08 WHERE IS_ACTIVE = 'FALSE'
AND DEPARTMENT_ID = '0' 
AND JOB_TITLE IN ('HR Manager', 'Financial Analyst', 'Business Analyst', 'Data Analyst');

SELECT FIRST_NAME AS NAME, LAST_NAME AS SURNAME, SALARY FROM EMPLOYEE_DETAILS WHERE SALARY BETWEEN 30000 AND 50000; 

SELECT * FROM EMPLOYEE_DETAILS WHERE FIRST_NAME LIKE 'A%';

DELETE FROM EMPLOYEE_DETAILS WHERE EMPLOYEE_ID BETWEEN 1 AND 5;

ALTER TABLE EMPLOYEE_DETAILS RENAME TO EMPLOYEE_DATABASE;

SELECT * FROM EMPLOYEE_DATABASE;

ALTER TABLE EMPLOYEE_DATABASE RENAME COLUMN FIRST_NAME TO NAME; 
ALTER TABLE EMPLOYEE_DATABASE RENAME COLUMN LAST_NAME TO SURNAME;

ALTER TABLE EMPLOYEE_DATABASE ADD COLUMN STATE VARCHAR NOT NULL DEFAULT 'NOT FOUND';

UPDATE EMPLOYEE_DATABASE SET STATE = 'INDIA' WHERE IS_ACTIVE = 'TRUE';
UPDATE EMPLOYEE_DATABASE SET STATE = 'USA' WHERE IS_ACTIVE = 'FALSE';



